"""empty message

Revision ID: b0dd54622276
Revises: 
Create Date: 2019-09-11 15:15:53.348336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0dd54622276'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coordinates',
    sa.Column('id', sa.Float(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('flight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight'], ['flight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('start_coords_id', sa.Integer(), nullable=True),
    sa.Column('end_coords_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['end_coords_id'], ['coordinates.id'], ),
    sa.ForeignKeyConstraint(['start_coords_id'], ['coordinates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flights_to_comps',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('comp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comp_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
    sa.PrimaryKeyConstraint('flight_id', 'comp_id')
    )
    op.create_table('flights_to_soldiers',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('soldier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
    sa.ForeignKeyConstraint(['soldier_id'], ['soldier.id'], ),
    sa.PrimaryKeyConstraint('flight_id', 'soldier_id')
    )
    op.create_table('soldier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soldier')
    op.drop_table('flights_to_soldiers')
    op.drop_table('flights_to_comps')
    op.drop_table('flight')
    op.drop_table('coordinates')
    op.drop_table('component')
    # ### end Alembic commands ###
