"""empty message

Revision ID: b5b999c45602
Revises: 
Create Date: 2019-08-29 15:43:22.406989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b999c45602'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=64), nullable=True),
    sa.Column('alive', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flights_to_comps',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('comp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comp_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
    sa.PrimaryKeyConstraint('flight_id', 'comp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights_to_comps')
    op.drop_table('flight')
    op.drop_table('component')
    # ### end Alembic commands ###
